baseurl = "https://danielloader.github.io/"
languageCode = "en-gb"
title = "RAF Waddington Heritage Centre"
theme = "creative"
googleAnalytics = ""

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # All projects of the portfolio are defined in their own files.
    # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
    # folder into the 'data' directory at the root of this Hugo site.
    # For more information take a look at the README.

    # To provide some metadata for search engines feel free to add some
    # information about you and your website.
    name = "Your name"
    description = "Your description"

    # The path must be relative to the static folder
    favicon = "favicon.ico"


    # Navigation
    [params.navigation]
        brand = ""

        [params.navigation.links]
            about = "About"
            gallery = "Photo Gallery"
            information = "Tour Information"
            contact  = "Book Tour"


    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan = "RAF Waddington"
        subslogan = "Heritage Centre"
        subtitle =  """Blurb about the place goes here.<br>
                    Lorem ipsum dolor sit amet, iisque prodesset moderatius in sed, te vix oratio tempor graeci. 
                    Odio verear contentiones per an, ad ludus assentior eum. Quo ei graeco maiorum. Per an sumo 
                    veniam aliquip, no duis scribentur comprehensam usu. Id vel choro soluta adipisci, debet noster 
                    vulputate an sit."""
        buttonText = "Find out more"


    # About section
    [params.about]
        headline    = "We've got what you need!"
        description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
        buttonText  = "Book a Tour!"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Contact section
    [params.contact]
        headline = "Booking a Tour"
        description = "Please fill out this form to send us an email to get back to you about a prospective tour booking"
        form = "true"

    # Google Maps section
    [params.location]
        latitude  = "53.1666836"
        longitude = "-0.5296903"
        zoom = "15"
        description = "RAF Waddington Heritage Centre<br>High Dike, Waddington, Lincoln<br>LN5 9YA"
